name: Deploy Golang App to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: 2202 # Sesuaikan dengan port SSH di server

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Pastikan SSH_HOST di-set
          if [[ -z "$SSH_HOST" ]]; then echo "Error: SSH_HOST is not set"; exit 1; fi

          # Tambahkan host ke known_hosts
          ssh-keyscan -H "$SSH_HOST" 2>/dev/null >> ~/.ssh/known_hosts || echo "Failed to add known_hosts"

          # Debugging: Lihat apakah SSH bisa connect
          echo "Connecting to SSH: $SSH_USER@$SSH_HOST on port $SSH_PORT"
          ssh -v -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'SSH connected!'"

          # Jika berhasil, lanjutkan deployment
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
            cd /var/www/open_api_golang
            git reset --hard
            git pull origin master
            sudo systemctl restart open_api_golang
          EOF
