name: Deploy to VPS

on:
  push:
    branches:
      - master # Sesuaikan dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa -p 2202 yusharwz@yusharwz.my.id << 'EOF'
            cd /var/www/open_api_golang
            git reset --hard
            git pull origin master
            sudo systemctl restart open_api_golang
            echo 'Deployment successful!'
          EOF
