name: Deploy Go App to VPS

on:
  push:
    branches:
      - master # Jalankan hanya ketika push ke branch `master`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure SSH Directory Exists
        run: mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh

      - name: Add Private Key to SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Connected !"
